sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
